const now = () => new Date();

const organizations = [
  { id: 'supra', name: 'Supra Multi-Specialty Hospital', segment: 'hospital', config: { token_budget: 4000, derivability_threshold: 0.7 } }
];

const hierarchyLevels = [
  { id: 'HL-01', orgId: 'supra', levelNumber: 1, levelName: 'Hospital', department: null, parentIds: [], zone: 1 },
  { id: 'HL-03-CLIN', orgId: 'supra', levelNumber: 3, levelName: 'Clinical Division', department: null, parentIds: ['HL-01'], zone: 1 },
  { id: 'HL-GLOBAL', orgId: 'supra', levelNumber: 3, levelName: 'Global Constraints', department: null, parentIds: ['HL-01'], zone: 2 },
  { id: 'HL-05-MED', orgId: 'supra', levelNumber: 5, levelName: 'Gen Medicine Department', department: 'medicine', parentIds: ['HL-03-CLIN'], zone: 1 },
  { id: 'HL-05-ORTHO', orgId: 'supra', levelNumber: 5, levelName: 'Orthopaedics Department', department: 'ortho', parentIds: ['HL-03-CLIN'], zone: 1 },
  { id: 'HL-08-MED', orgId: 'supra', levelNumber: 8, levelName: 'Medicine General', department: 'medicine', parentIds: ['HL-05-MED'], zone: 1 },
  { id: 'HL-10-MED-W', orgId: 'supra', levelNumber: 10, levelName: 'Medicine Ward', department: 'medicine', parentIds: ['HL-08-MED'], zone: 1 },
  { id: 'HL-12-PADMA', orgId: 'supra', levelNumber: 12, levelName: 'Patient: Padma', department: 'medicine', parentIds: ['HL-10-MED-W'], zone: 1 }
];

const users = [
  { id: 'U-MEERA', orgId: 'supra', name: 'Dr. Meera (HOD Medicine)', role: 'HOD', department: 'medicine', ceilingLevel: 4, applicableCohorts: ['fasting_diabetic', 'warfarin_patient'], hasCompletedOnboarding: true },
  { id: 'U-ANANYA', orgId: 'supra', name: 'Dr. Ananya (Junior)', role: 'EDITOR', department: 'medicine', ceilingLevel: 8, applicableCohorts: ['fasting_diabetic'], hasCompletedOnboarding: false },
  { id: 'U-PRIYA', orgId: 'supra', name: 'Nurse Priya', role: 'VIEWER', department: 'ortho', ceilingLevel: 10, applicableCohorts: [], hasCompletedOnboarding: false },
  { id: 'U-VIKRAM', orgId: 'supra', name: 'Dr. Vikram (HOD Ortho)', role: 'HOD', department: 'ortho', ceilingLevel: 4, applicableCohorts: ['warfarin_patient'], hasCompletedOnboarding: true }
];

const patients = [
  { id: 'PAT-PADMA', orgId: 'supra', name: 'Mrs. Padma', age: 62, gender: 'F', department: 'medicine', conditions: ['Type 2 DM', 'Hypertension'], cohortTags: ['fasting_diabetic'], notes: 'On Metformin 1000mg BD + Glimepiride 2mg. Observes Ekadashi fasting twice monthly.' },
  { id: 'PAT-RAJAN', orgId: 'supra', name: 'Mr. Rajan', age: 68, gender: 'M', department: 'ortho', conditions: ['AF on Warfarin', 'GI bleed history'], cohortTags: ['warfarin_patient'], notes: 'Warfarin 5mg daily. INR target 2.0-3.0. STRICTLY no NSAIDs.' }
];

const questions = [
  { id: 'Q-H01', orgId: 'supra', level: 'HOSPITAL', department: null, targetRole: null, cohortTag: null, priority: 0, questionText: 'What is the most dangerous thing a new doctor could do at Supra?', typeHint: 'CONSTRAINT', targetHierarchyLevel: 'HL-01', importanceDefault: 0.95, placeholderText: 'e.g., Prescribe NSAIDs to anticoagulated patients' },
  { id: 'Q-H02', orgId: 'supra', level: 'HOSPITAL', department: null, targetRole: null, cohortTag: null, priority: 0, questionText: 'What infection control measure does Supra enforce for ALL invasive procedures?', typeHint: 'CONSTRAINT', targetHierarchyLevel: 'HL-GLOBAL', importanceDefault: 0.93, placeholderText: 'e.g., Two-person verification, hand hygiene compliance' },
  { id: 'Q-H03', orgId: 'supra', level: 'HOSPITAL', department: null, targetRole: null, cohortTag: null, priority: 1, questionText: "What is Supra's policy on verbal medication orders?", typeHint: 'ANTI_PATTERN', targetHierarchyLevel: 'HL-GLOBAL', importanceDefault: 0.90, placeholderText: 'e.g., Never accept without written confirmation within 1 hour' },
  { id: 'Q-H04', orgId: 'supra', level: 'HOSPITAL', department: null, targetRole: null, cohortTag: null, priority: 1, questionText: "What are Supra's emergency codes (Blue, Red, Pink)?", typeHint: 'FACT', targetHierarchyLevel: 'HL-GLOBAL', importanceDefault: 0.70, placeholderText: 'e.g., Blue=cardiac arrest, Red=fire, Pink=infant abduction' },
  { id: 'Q-H05', orgId: 'supra', level: 'HOSPITAL', department: null, targetRole: null, cohortTag: null, priority: 2, questionText: 'What patient identification method does Supra require?', typeHint: 'CONSTRAINT', targetHierarchyLevel: 'HL-GLOBAL', importanceDefault: 0.92, placeholderText: 'e.g., Two identifiers: name + DOB or name + hospital ID' },
  { id: 'Q-H06', orgId: 'supra', level: 'HOSPITAL', department: null, targetRole: null, cohortTag: null, priority: 2, questionText: 'What fall risk assessment tool does Supra use?', typeHint: 'DECISION', targetHierarchyLevel: 'HL-GLOBAL', importanceDefault: 0.78, placeholderText: 'e.g., Morse Fall Scale on admission and every shift change' },
  { id: 'Q-H07', orgId: 'supra', level: 'HOSPITAL', department: null, targetRole: null, cohortTag: null, priority: 3, questionText: 'What antibiotic stewardship policy does Supra enforce?', typeHint: 'CONSTRAINT', targetHierarchyLevel: 'HL-GLOBAL', importanceDefault: 0.85, placeholderText: 'e.g., 72-hour empiric review mandatory, pharmacy auto-alerts' },

  { id: 'Q-MED01', orgId: 'supra', level: 'DEPARTMENT', department: 'medicine', targetRole: null, cohortTag: null, priority: 0, questionText: "What is your department's first-line protocol for suspected sepsis?", typeHint: 'DECISION', targetHierarchyLevel: 'HL-05-MED', importanceDefault: 0.92, placeholderText: 'e.g., Blood cultures before antibiotics, lactate within 1 hour' },
  { id: 'Q-MED02', orgId: 'supra', level: 'DEPARTMENT', department: 'medicine', targetRole: null, cohortTag: null, priority: 0, questionText: 'What is the biggest prescribing mistake a new Medicine doctor could make?', typeHint: 'ANTI_PATTERN', targetHierarchyLevel: 'HL-05-MED', importanceDefault: 0.88, placeholderText: 'e.g., Using insulin sliding scale as sole glycemic management' },
  { id: 'Q-MED03', orgId: 'supra', level: 'DEPARTMENT', department: 'medicine', targetRole: null, cohortTag: null, priority: 1, questionText: "What are your department's formulary brand preferences?", typeHint: 'FACT', targetHierarchyLevel: 'HL-05-MED', importanceDefault: 0.65, placeholderText: 'e.g., Calpol for Paracetamol, Omez for Omeprazole' },
  { id: 'Q-MED04', orgId: 'supra', level: 'DEPARTMENT', department: 'medicine', targetRole: null, cohortTag: null, priority: 1, questionText: "What is your department's IV antibiotic step-down policy?", typeHint: 'DECISION', targetHierarchyLevel: 'HL-08-MED', importanceDefault: 0.72, placeholderText: 'e.g., Step down to oral at 48-72 hours when clinically stable' },
  { id: 'Q-MED05', orgId: 'supra', level: 'DEPARTMENT', department: 'medicine', targetRole: null, cohortTag: null, priority: 2, questionText: 'What specialty clinics does Medicine run and on which days?', typeHint: 'FACT', targetHierarchyLevel: 'HL-05-MED', importanceDefault: 0.45, placeholderText: 'e.g., DM clinic Mon/Wed, Hypertension Tue/Thu' },
  { id: 'Q-MED06', orgId: 'supra', level: 'DEPARTMENT', department: 'medicine', targetRole: null, cohortTag: null, priority: 2, questionText: 'What contrast allergy pre-treatment protocol does Medicine follow?', typeHint: 'CONSTRAINT', targetHierarchyLevel: 'HL-05-MED', importanceDefault: 0.85, placeholderText: 'e.g., Hydrocortisone 200mg IV + Chlorpheniramine 1hr before' },
  { id: 'Q-MED07', orgId: 'supra', level: 'DEPARTMENT', department: 'medicine', targetRole: null, cohortTag: null, priority: 3, questionText: "What is your department's approach to anticoagulation bridging?", typeHint: 'DECISION', targetHierarchyLevel: 'HL-08-MED', importanceDefault: 0.75, placeholderText: 'e.g., LMWH bridging for mechanical valves, no bridging for AF' },

  { id: 'Q-ORT01', orgId: 'supra', level: 'DEPARTMENT', department: 'ortho', targetRole: null, cohortTag: null, priority: 0, questionText: "What is Ortho's first-line post-surgical pain management protocol?", typeHint: 'DECISION', targetHierarchyLevel: 'HL-05-ORTHO', importanceDefault: 0.88, placeholderText: 'e.g., Paracetamol 650mg QDS, escalate to Tramadol if VAS > 6' },
  { id: 'Q-ORT02', orgId: 'supra', level: 'DEPARTMENT', department: 'ortho', targetRole: null, cohortTag: null, priority: 0, questionText: 'What DVT prophylaxis does Ortho require for all surgical patients?', typeHint: 'CONSTRAINT', targetHierarchyLevel: 'HL-05-ORTHO', importanceDefault: 0.93, placeholderText: 'e.g., Enoxaparin 40mg SC daily starting 12 hours post-op' },
  { id: 'Q-ORT03', orgId: 'supra', level: 'DEPARTMENT', department: 'ortho', targetRole: null, cohortTag: null, priority: 1, questionText: 'What is the minimum stay for TKR patients and why?', typeHint: 'ANTI_PATTERN', targetHierarchyLevel: 'HL-05-ORTHO', importanceDefault: 0.91, placeholderText: 'e.g., 48 hours minimum — past incident with early DVT' },
  { id: 'Q-ORT04', orgId: 'supra', level: 'DEPARTMENT', department: 'ortho', targetRole: null, cohortTag: null, priority: 2, questionText: 'What implant vendor does Ortho prefer and why?', typeHint: 'DECISION', targetHierarchyLevel: 'HL-05-ORTHO', importanceDefault: 0.72, placeholderText: 'e.g., Zimmer Biomet, based on 3-year outcomes review' },
  { id: 'Q-ORT05', orgId: 'supra', level: 'DEPARTMENT', department: 'ortho', targetRole: null, cohortTag: null, priority: 2, questionText: 'What is the Ortho Ward bed capacity and overflow plan?', typeHint: 'FACT', targetHierarchyLevel: 'HL-05-ORTHO', importanceDefault: 0.50, placeholderText: 'e.g., 45 beds, overflow to Medicine Ward during winter' },

  { id: 'Q-R-EDITOR01', orgId: 'supra', level: 'ROLE', department: null, targetRole: 'EDITOR', cohortTag: null, priority: 0, questionText: 'As a junior doctor, what must you ALWAYS check before prescribing any new medication?', typeHint: 'CONSTRAINT', targetHierarchyLevel: 'HL-03-CLIN', importanceDefault: 0.90, placeholderText: 'e.g., Allergy history, current medications, renal function' },
  { id: 'Q-R-EDITOR02', orgId: 'supra', level: 'ROLE', department: null, targetRole: 'EDITOR', cohortTag: null, priority: 1, questionText: 'What is the most common mistake junior doctors make when ordering investigations?', typeHint: 'ANTI_PATTERN', targetHierarchyLevel: 'HL-03-CLIN', importanceDefault: 0.82, placeholderText: 'e.g., Ordering CT without trying ultrasound first' },
  { id: 'Q-R-EDITOR03', orgId: 'supra', level: 'ROLE', department: null, targetRole: 'EDITOR', cohortTag: null, priority: 2, questionText: 'What escalation procedure do you follow when a patient deteriorates on your watch?', typeHint: 'DECISION', targetHierarchyLevel: 'HL-03-CLIN', importanceDefault: 0.85, placeholderText: 'e.g., Call senior within 15 min, MET team if no response in 30 min' },
  { id: 'Q-R-VIEWER01', orgId: 'supra', level: 'ROLE', department: null, targetRole: 'VIEWER', cohortTag: null, priority: 0, questionText: 'As a nurse, what is your most critical handover responsibility?', typeHint: 'CONSTRAINT', targetHierarchyLevel: 'HL-03-CLIN', importanceDefault: 0.88, placeholderText: 'e.g., SBAR format handover, pending labs, clinical concerns' },
  { id: 'Q-R-VIEWER02', orgId: 'supra', level: 'ROLE', department: null, targetRole: 'VIEWER', cohortTag: null, priority: 1, questionText: 'What must you document every time you administer a controlled substance?', typeHint: 'CONSTRAINT', targetHierarchyLevel: 'HL-03-CLIN', importanceDefault: 0.92, placeholderText: 'e.g., Drug name, dose, time, route, patient response, witness' },
  { id: 'Q-R-HOD01', orgId: 'supra', level: 'ROLE', department: null, targetRole: 'HOD', cohortTag: null, priority: 1, questionText: 'What governance decision has your department made in the last 6 months that all staff should know?', typeHint: 'DECISION', targetHierarchyLevel: 'HL-05-MED', importanceDefault: 0.80, placeholderText: 'e.g., Tightened sepsis lactate window from 3 hours to 1 hour' },

  { id: 'Q-C-FAST01', orgId: 'supra', level: 'COHORT', department: 'medicine', targetRole: null, cohortTag: 'fasting_diabetic', priority: 0, questionText: 'What medication adjustment does Supra follow for diabetic patients observing religious fasts?', typeHint: 'CONSTRAINT', targetHierarchyLevel: 'HL-05-MED', importanceDefault: 0.90, placeholderText: 'e.g., Adjust insulin timing not dose, skip Glimepiride on fast days' },
  { id: 'Q-C-FAST02', orgId: 'supra', level: 'COHORT', department: 'medicine', targetRole: null, cohortTag: 'fasting_diabetic', priority: 1, questionText: "What monitoring protocol applies during a patient's fasting period?", typeHint: 'DECISION', targetHierarchyLevel: 'HL-08-MED', importanceDefault: 0.78, placeholderText: 'e.g., BG every 4 hours, break fast immediately if BG < 70' },
  { id: 'Q-C-FAST03', orgId: 'supra', level: 'COHORT', department: 'medicine', targetRole: null, cohortTag: 'fasting_diabetic', priority: 2, questionText: 'What has your experience been with hypoglycemia during religious fasts?', typeHint: 'FACT', targetHierarchyLevel: 'HL-08-MED', importanceDefault: 0.60, placeholderText: 'e.g., 3 incidents in 2025, all Glimepiride patients, none on Metformin alone' },
  { id: 'Q-C-WARF01', orgId: 'supra', level: 'COHORT', department: null, targetRole: null, cohortTag: 'warfarin_patient', priority: 0, questionText: 'What medications are ABSOLUTELY contraindicated with Warfarin at Supra?', typeHint: 'CONSTRAINT', targetHierarchyLevel: 'HL-GLOBAL', importanceDefault: 0.98, placeholderText: 'e.g., All NSAIDs — ibuprofen, aspirin, diclofenac' },
  { id: 'Q-C-WARF02', orgId: 'supra', level: 'COHORT', department: null, targetRole: null, cohortTag: 'warfarin_patient', priority: 1, questionText: 'What INR monitoring schedule does Supra follow for Warfarin patients?', typeHint: 'DECISION', targetHierarchyLevel: 'HL-05-MED', importanceDefault: 0.82, placeholderText: 'e.g., Weekly until stable, then every 2-4 weeks' }
];

const preAnsweredNodes = [
  { id: 'N-QH01', orgId: 'supra', hierarchyLevelId: 'HL-01', type: 'CONSTRAINT', title: 'NSAID Contraindication in Anticoagulated Patients', content: 'CRITICAL: Never prescribe NSAIDs (ibuprofen, aspirin, diclofenac) to patients on anticoagulants (Warfarin, Dabigatran, Rivaroxaban). Risk of life-threatening GI bleed. Use Paracetamol for pain. Supra incident 2024: GI bleed from NSAID+Warfarin interaction.', importance: 0.95, zone: 2, status: 'ACTIVE', department: null, derivabilityScore: 0.08, sourceQuestionId: 'Q-H01', sourceType: 'QUESTION', createdBy: 'U-MEERA', decayProfile: 'FIXED', retrievalWeight: 0.99, injectionWeight: 0.99, compressionMode: 'FULL' },
  { id: 'N-QH02', orgId: 'supra', hierarchyLevelId: 'HL-GLOBAL', type: 'CONSTRAINT', title: 'Sterile Technique for All Invasive Procedures', content: 'Full sterile technique mandatory for ALL invasive procedures including IV cannulation, catheterization, and lumbar puncture. Surgical hand scrub + sterile gloves + draping. No shortcuts, no exceptions.', importance: 0.93, zone: 2, status: 'ACTIVE', department: null, derivabilityScore: 0.15, sourceQuestionId: 'Q-H02', sourceType: 'QUESTION', createdBy: 'U-MEERA', decayProfile: 'FIXED', retrievalWeight: 0.96, injectionWeight: 0.96, compressionMode: 'FULL' },
  { id: 'N-QH03', orgId: 'supra', hierarchyLevelId: 'HL-GLOBAL', type: 'ANTI_PATTERN', title: 'No Verbal Medication Orders Without Confirmation', content: 'NEVER accept verbal medication orders without written/electronic confirmation within 1 hour. Supra incident 2023: wrong dose from mishearing. Only exception: cardiac arrest. Read-back mandatory for all verbal orders.', importance: 0.90, zone: 2, status: 'ACTIVE', department: null, derivabilityScore: 0.10, sourceQuestionId: 'Q-H03', sourceType: 'QUESTION', createdBy: 'U-MEERA', decayProfile: 'SLOW_36M', retrievalWeight: 0.90, injectionWeight: 0.90, compressionMode: 'CONCISE' },
  { id: 'N-QMED01', orgId: 'supra', hierarchyLevelId: 'HL-05-MED', type: 'DECISION', title: 'Supra Sepsis Protocol v3', content: 'Sepsis Bundle v3 (2026): Blood cultures BEFORE antibiotics. Lactate within 1 HOUR (not 3 — tightened from v2). 30mL/kg crystalloid for hypotension. Vasopressors if MAP < 65 after fluids. Piperacillin-Tazobactam empiric.', importance: 0.92, zone: 1, status: 'ACTIVE', department: 'medicine', derivabilityScore: 0.12, sourceQuestionId: 'Q-MED01', sourceType: 'QUESTION', createdBy: 'U-MEERA', decayProfile: 'STANDARD_24M', retrievalWeight: 0.92, injectionWeight: 0.92, compressionMode: 'FULL' },
  { id: 'N-QMED02', orgId: 'supra', hierarchyLevelId: 'HL-05-MED', type: 'ANTI_PATTERN', title: 'Never Use Insulin Sliding Scale Alone', content: 'Do NOT use insulin sliding scale as sole glycemic management. Past incident: DKA patient on sliding scale only, readmitted 48 hours. ALWAYS include basal insulin. Sliding scale supplements, never replaces.', importance: 0.88, zone: 1, status: 'ACTIVE', department: 'medicine', derivabilityScore: 0.18, sourceQuestionId: 'Q-MED02', sourceType: 'QUESTION', createdBy: 'U-MEERA', decayProfile: 'SLOW_36M', retrievalWeight: 0.88, injectionWeight: 0.88, compressionMode: 'CONCISE' },
  { id: 'N-QCFAST01', orgId: 'supra', hierarchyLevelId: 'HL-05-MED', type: 'CONSTRAINT', title: 'Fasting Diabetic Medication Adjustment', content: 'For diabetic patients observing religious fasts (Ekadashi, Ramadan): adjust insulin TIMING not DOSE. Pre-fast: shift long-acting to evening. Skip Glimepiride on fast days. Continue Metformin with evening meal. Monitor BG q4h. Break fast immediately if BG < 70.', importance: 0.90, zone: 1, status: 'ACTIVE', department: 'medicine', derivabilityScore: 0.05, sourceQuestionId: 'Q-C-FAST01', sourceType: 'QUESTION', createdBy: 'U-MEERA', decayProfile: 'FIXED', retrievalWeight: 0.95, injectionWeight: 0.98, compressionMode: 'FULL' },
  { id: 'N-QCFAST02', orgId: 'supra', hierarchyLevelId: 'HL-08-MED', type: 'DECISION', title: 'Fasting Period Monitoring Protocol', content: 'During patient fasting: BG every 4 hours minimum. If symptomatic (dizziness, sweating): immediate BG. Break fast if BG < 70 or > 300. Document all readings in fasting monitoring chart. Alert duty doctor if 2 consecutive readings abnormal.', importance: 0.78, zone: 1, status: 'ACTIVE', department: 'medicine', derivabilityScore: 0.08, sourceQuestionId: 'Q-C-FAST02', sourceType: 'QUESTION', createdBy: 'U-MEERA', decayProfile: 'STANDARD_24M', retrievalWeight: 0.83, injectionWeight: 0.88, compressionMode: 'FULL' }
];

const preAnsweredAnswers = [
  { id: 'A-MEERA-H01', questionId: 'Q-H01', userId: 'U-MEERA', answerText: 'Prescribe NSAIDs to anticoagulated patients', nodeId: 'N-QH01', answeredAt: new Date('2026-01-15T04:30:00.000Z') },
  { id: 'A-MEERA-H02', questionId: 'Q-H02', userId: 'U-MEERA', answerText: 'Full sterile technique for all invasive procedures', nodeId: 'N-QH02', answeredAt: new Date('2026-01-15T04:45:00.000Z') },
  { id: 'A-MEERA-H03', questionId: 'Q-H03', userId: 'U-MEERA', answerText: 'Never accept verbal orders without written confirmation in 1 hour', nodeId: 'N-QH03', answeredAt: new Date('2026-01-15T05:00:00.000Z') },
  { id: 'A-MEERA-MED01', questionId: 'Q-MED01', userId: 'U-MEERA', answerText: 'Sepsis v3: cultures before abx, lactate 1 hour, Pip-Tazo empiric', nodeId: 'N-QMED01', answeredAt: new Date('2026-01-16T03:30:00.000Z') },
  { id: 'A-MEERA-MED02', questionId: 'Q-MED02', userId: 'U-MEERA', answerText: 'Never insulin sliding scale alone — always basal + supplemental', nodeId: 'N-QMED02', answeredAt: new Date('2026-01-16T03:45:00.000Z') },
  { id: 'A-MEERA-FAST01', questionId: 'Q-C-FAST01', userId: 'U-MEERA', answerText: 'Adjust timing not dose, skip Glimepiride, continue Metformin, BG q4h', nodeId: 'N-QCFAST01', answeredAt: new Date('2026-01-17T04:30:00.000Z') },
  { id: 'A-MEERA-FAST02', questionId: 'Q-C-FAST02', userId: 'U-MEERA', answerText: 'BG q4h, break fast if <70 or >300, document in fasting chart', nodeId: 'N-QCFAST02', answeredAt: new Date('2026-01-17T04:45:00.000Z') }
];

const patientNodes = [
  { id: 'N-PAT-PADMA-01', orgId: 'supra', hierarchyLevelId: 'HL-12-PADMA', type: 'FACT', title: 'Patient Padma: Medication Profile', content: 'Padma, 62F. Type 2 DM. Current medications: Metformin 1000mg BD, Glimepiride 2mg OD, Telmisartan 40mg OD. Allergies: Sulfonamide (rash). HbA1c: 7.8% (last 3 months ago).', importance: 0.85, zone: 1, status: 'ACTIVE', department: 'medicine', derivabilityScore: 0.02, sourceQuestionId: null, sourceType: 'PATIENT', createdBy: 'U-MEERA', decayProfile: 'FAST_12M', retrievalWeight: 0.92, injectionWeight: 0.95, compressionMode: 'FULL' },
  { id: 'N-PAT-PADMA-02', orgId: 'supra', hierarchyLevelId: 'HL-12-PADMA', type: 'FACT', title: 'Patient Padma: Ekadashi Fasting Pattern', content: 'Mrs. Padma observes Ekadashi fasting twice monthly (11th day of each lunar fortnight). Complete fast from sunrise to next morning. Adjusted protocol: skip Glimepiride, continue Metformin with evening meal when she breaks fast. 3 episodes of mild hypoglycemia in 2025 — all on fast days before protocol adjustment.', importance: 0.82, zone: 1, status: 'ACTIVE', department: 'medicine', derivabilityScore: 0.01, sourceQuestionId: null, sourceType: 'PATIENT', createdBy: 'U-MEERA', decayProfile: 'FAST_12M', retrievalWeight: 0.92, injectionWeight: 0.95, compressionMode: 'FULL' },
  { id: 'N-PAT-PADMA-03', orgId: 'supra', hierarchyLevelId: 'HL-12-PADMA', type: 'DECISION', title: 'Patient Padma: Adjusted Fasting Protocol', content: 'For Padma specifically: skip Glimepiride 2mg on Ekadashi days ONLY. Continue Metformin 1000mg with evening meal (when she breaks fast). BG monitoring: at start of fast, every 4 hours, and before bed. Family instructed: glucometer at home, juice ready, call if BG < 70.', importance: 0.88, zone: 1, status: 'ACTIVE', department: 'medicine', derivabilityScore: 0.01, sourceQuestionId: null, sourceType: 'PATIENT', createdBy: 'U-MEERA', decayProfile: 'STANDARD_24M', retrievalWeight: 0.95, injectionWeight: 0.99, compressionMode: 'FULL' }
];

module.exports = { organizations, hierarchyLevels, users, patients, questions, preAnsweredNodes, preAnsweredAnswers, patientNodes };
